
VERSION = "2.0.0"

[DOCUMENTATION]
ORG_NAME = "Laam Project"
ORG_URL = "https://laam.online"
ORG_LOGO = "https://fond-magenta-owpureihfj.edgeone.app/20250802_225108.png"
ORG_DESCRIPTION = "Laam is a native token built on Stellar blockchain."

[[CURRENCIES]]
code = "LAAM"
issuer = "GAL4ECDAXNBMJYFCWIJ32HKVIRLCNEXY664CAZYI3EINQWPLXTMEPR64"
display_decimals = 2
name = "Laam Coin"
desc = "Laam Coin is a Stellar native asset with a fixed supply of 1,335,577 tokens, designed for modern decentralized finance use cases."
image = "https://fond-magenta-owpureihfj.edgeone.app/20250802_225108.png"
